version: '3'
services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    network_mode: host
    user: "${UID_GID}"
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./public/uploads:/opt/app/public/uploads
    restart:
      always
